import { type SiteImage, siteImages } from './site-images';

const HEADING_PHOTO_MATCHES: readonly { needle: string; image: SiteImage }[] = [
  { needle: 'privacy', image: siteImages.privacyPolicy },
  { needle: 'terms', image: siteImages.termsOfService },
  { needle: 'accessib', image: siteImages.accessibility },
  { needle: 'fair housing', image: siteImages.fairHousing },
  { needle: 'equal housing', image: siteImages.fairHousing },
  { needle: 'elementary', image: siteImages.elementaryCampus },
  { needle: 'middle', image: siteImages.schoolsSecondary },
  { needle: 'high school', image: siteImages.schoolsSecondary },
  { needle: 'secondary', image: siteImages.schoolsSecondary },
  { needle: 'school', image: siteImages.schools },
  { needle: 'campus', image: siteImages.schools },
  { needle: 'ccsd', image: siteImages.schools },
  { needle: 'healthcare', image: siteImages.healthcareNlv },
  { needle: 'hospital', image: siteImages.healthcareNlv },
  { needle: 'medical', image: siteImages.healthcareNlv },
  { needle: 'mls', image: siteImages.mlsData },
  { needle: 'listing data', image: siteImages.mlsData },
  { needle: 'property information', image: siteImages.mlsData },
  { needle: 'search live', image: siteImages.buyerSearch },
  { needle: 'listing photo', image: siteImages.listingMarketing },
  { needle: 'market an aliante listing', image: siteImages.listingMarketing },
  { needle: 'close', image: siteImages.buyerClose },
  { needle: 'closing', image: siteImages.buyerClose },
  { needle: 'escrow', image: siteImages.buyerClose },
  { needle: 'title', image: siteImages.buyerClose },
  { needle: 'offer', image: siteImages.writeOffer },
  { needle: 'contract', image: siteImages.writeOffer },
  { needle: 'pre-approv', image: siteImages.writeOffer },
  { needle: 'golf', image: siteImages.golfLotTour },
  { needle: 'fairway', image: siteImages.golfLotTour },
  { needle: 'tee', image: siteImages.golfLotTour },
  { needle: 'gate', image: siteImages.gatedHoa },
  { needle: 'controlled', image: siteImages.gatedHoa },
  { needle: 'guest list', image: siteImages.gatedHoa },
  { needle: 'cc&r', image: siteImages.gatedHoa },
  { needle: 'hoa', image: siteImages.hoaRules },
  { needle: 'occupancy', image: siteImages.hoaRules },
  { needle: 'dues', image: siteImages.hoaRules },
  { needle: 'sun city', image: siteImages.sunCityPlans },
  { needle: '55', image: siteImages.sunCityPlans },
  { needle: 'del webb', image: siteImages.sunCityPlans },
  { needle: 'floor plan', image: siteImages.sunCityPlans },
  { needle: 'incentive', image: siteImages.incentives },
  { needle: 'design-center', image: siteImages.incentives },
  { needle: 'buydown', image: siteImages.incentives },
  { needle: 'lennar', image: siteImages.newConstruction },
  { needle: 'horton', image: siteImages.newConstruction },
  { needle: 'builder', image: siteImages.newConstruction },
  { needle: 'new construction', image: siteImages.newConstruction },
  { needle: 'tule', image: siteImages.tuleSprings },
  { needle: 'prominence', image: siteImages.prominence },
  { needle: 'paseos', image: siteImages.paseos },
  { needle: 'desert willow', image: siteImages.desertWillows },
  { needle: 'club aliante', image: siteImages.clubAliante },
  { needle: 'park', image: siteImages.amenities },
  { needle: 'amenit', image: siteImages.amenities },
  { needle: 'pool', image: siteImages.amenities },
  { needle: 'open-access', image: siteImages.paseos },
  { needle: 'open access', image: siteImages.paseos },
  { needle: 'tour', image: siteImages.villageTour },
  { needle: 'village', image: siteImages.villageTour },
  { needle: 'comp', image: siteImages.pricingComps },
  { needle: 'cma', image: siteImages.pricingComps },
  { needle: 'pric', image: siteImages.pricingComps },
  { needle: 'rent', image: siteImages.rentalHoa },
  { needle: 'mortgage', image: siteImages.lenderMeeting },
  { needle: 'loan', image: siteImages.lenderMeeting },
  { needle: 'down payment', image: siteImages.lenderMeeting },
  { needle: 'office', image: siteImages.officeNap },
  { needle: 'nap', image: siteImages.officeNap },
  { needle: 'contact', image: siteImages.officeNap },
  { needle: 'license', image: siteImages.officeNap },
];

/**
 * Pick a heading-matched photo from H2/H3 text. Architecture and landscape only.
 * Fair Housing: never map “family,” “safe,” or school-quality language to a photo.
 */
export function headingMatchedImage(heading: string): SiteImage {
  const h = heading.toLowerCase();
  const match = HEADING_PHOTO_MATCHES.find((row) => h.includes(row.needle));
  return match?.image ?? siteImages.neighborhoods;
}
