import { type SiteImage, siteImages } from './site-images';

/**
 * First match wins. Keep needles long enough that they cannot hitchhike inside
 * unrelated words (e.g. “tee” in “street”, “gate” in “navigate”, “55” in a price).
 */
const HEADING_PHOTO_MATCHES: readonly { needle: string; image: SiteImage }[] = [
  { needle: 'privacy', image: siteImages.privacyPolicy },
  { needle: 'information we collect', image: siteImages.privacyPolicy },
  { needle: 'terms', image: siteImages.termsOfService },
  { needle: 'use of services', image: siteImages.termsOfService },
  { needle: 'lennar versus', image: siteImages.chooseBuilder },
  { needle: 'versus horton', image: siteImages.chooseBuilder },
  { needle: 'fair comparison', image: siteImages.compare },
  { needle: 'versus aliante', image: siteImages.tuleSprings },
  { needle: '89131', image: siteImages.tollBrothers },
  { needle: 'how i represent', image: siteImages.builderAdvocate },
  { needle: 'buyer agency at', image: siteImages.builderAdvocate },
  { needle: 'tri pointe', image: siteImages.triPointe },
  { needle: 'toll brothers', image: siteImages.tollBrothers },
  { needle: 'richmond', image: siteImages.richmondAmerican },
  { needle: 'cash flow', image: siteImages.investment },
  { needle: 'who manages', image: siteImages.propertyManagement },
  { needle: 'property management', image: siteImages.propertyManagement },
  { needle: 'hidden cost', image: siteImages.mortgage },
  { needle: 'interest rate', image: siteImages.lenderMeeting },
  { needle: 'how rates', image: siteImages.lenderMeeting },
  { needle: 'pre-listing', image: siteImages.sellerPrep },
  { needle: 'market report', image: siteImages.marketReport },
  { needle: 'buyer representation', image: siteImages.buyerTour },
  { needle: 'selling an aliante', image: siteImages.sellerPrep },
  { needle: 'our team', image: siteImages.about },
  { needle: 'home valuation', image: siteImages.homeValuation },
  { needle: 'hyperlocal', image: siteImages.specialistStreet },
  { needle: 'investment', image: siteImages.investment },
  { needle: 'accessib', image: siteImages.accessibility },
  { needle: 'fair housing', image: siteImages.fairHousing },
  { needle: 'equal housing', image: siteImages.fairHousing },
  { needle: 'elementary', image: siteImages.elementaryCampus },
  { needle: 'middle', image: siteImages.schoolsSecondary },
  { needle: 'high school', image: siteImages.schoolsSecondary },
  { needle: 'secondary', image: siteImages.schoolsSecondary },
  { needle: 'school', image: siteImages.schools },
  { needle: 'campus', image: siteImages.schools },
  { needle: 'ccsd', image: siteImages.schools },
  { needle: 'healthcare', image: siteImages.healthcareNlv },
  { needle: 'hospital', image: siteImages.healthcareNlv },
  { needle: 'medical', image: siteImages.healthcareNlv },
  { needle: 'mls', image: siteImages.mlsData },
  { needle: 'listing data', image: siteImages.mlsData },
  { needle: 'property information', image: siteImages.mlsData },
  { needle: 'search live', image: siteImages.buyerSearch },
  { needle: 'listing photo', image: siteImages.listingMarketing },
  { needle: 'market an aliante listing', image: siteImages.listingMarketing },
  { needle: 'closing', image: siteImages.buyerClose },
  { needle: 'escrow', image: siteImages.buyerClose },
  { needle: 'title insurance', image: siteImages.buyerClose },
  { needle: 'title compan', image: siteImages.buyerClose },
  { needle: 'title and escrow', image: siteImages.buyerClose },
  { needle: 'offer', image: siteImages.writeOffer },
  { needle: 'contract expertise', image: siteImages.contractReview },
  { needle: 'contract review', image: siteImages.contractReview },
  { needle: 'contract', image: siteImages.writeOffer },
  { needle: 'pre-approv', image: siteImages.lenderMeeting },
  { needle: 'golf', image: siteImages.golfLotTour },
  { needle: 'fairway', image: siteImages.golfLotTour },
  { needle: 'gated', image: siteImages.gatedHoa },
  { needle: 'gatehouse', image: siteImages.gatedHoa },
  { needle: 'controlled-access', image: siteImages.gatedHoa },
  { needle: 'controlled access', image: siteImages.gatedHoa },
  { needle: 'guest list', image: siteImages.gatedHoa },
  { needle: 'cc&r', image: siteImages.gatedHoa },
  { needle: 'hoa', image: siteImages.hoaRules },
  { needle: 'occupancy', image: siteImages.hoaRules },
  { needle: 'dues', image: siteImages.hoaRules },
  { needle: 'sun city', image: siteImages.sunCityPlans },
  { needle: '55+', image: siteImages.sunCityPlans },
  { needle: 'age-qualif', image: siteImages.sunCityPlans },
  { needle: 'del webb', image: siteImages.sunCityPlans },
  { needle: 'floor plan', image: siteImages.sunCityPlans },
  { needle: 'walkthrough', image: siteImages.constructionWalkthrough },
  { needle: 'punch list', image: siteImages.constructionWalkthrough },
  { needle: 'never been lived', image: siteImages.constructionWalkthrough },
  { needle: 'warranty', image: siteImages.constructionWalkthrough },
  { needle: 'lot selection', image: siteImages.constructionLot },
  { needle: 'vacant lot', image: siteImages.constructionLot },
  { needle: 'framing', image: siteImages.constructionFraming },
  { needle: 'pre-drywall', image: siteImages.constructionFraming },
  { needle: 'design center', image: siteImages.constructionDesign },
  { needle: 'design-center', image: siteImages.constructionDesign },
  { needle: 'community selection', image: siteImages.constructionSelect },
  { needle: 'model home', image: siteImages.constructionSelect },
  { needle: 'volume builder', image: siteImages.volumeBuilders },
  { needle: 'more-custom', image: siteImages.tollBrothers },
  { needle: 'shopping', image: siteImages.shoppingAliante },
  { needle: 'dining', image: siteImages.shoppingAliante },
  { needle: 'casino', image: siteImages.shoppingAliante },
  { needle: 'nearby', image: siteImages.nearbyAliante },
  { needle: 'explore the neighborhood', image: siteImages.villageTour },
  { needle: 'transport', image: siteImages.i215Access },
  { needle: 'beltway', image: siteImages.i215Access },
  { needle: '215', image: siteImages.i215Access },
  { needle: 'google review', image: siteImages.googleReviews },
  { needle: 'proven', image: siteImages.googleReviews },
  { needle: 'schedule', image: siteImages.scheduleConsult },
  { needle: 'calendly', image: siteImages.scheduleConsult },
  { needle: 'client-first', image: siteImages.scheduleConsult },
  { needle: 'client first', image: siteImages.scheduleConsult },
  { needle: 'email', image: siteImages.emailOffice },
  { needle: 'license', image: siteImages.licenseCredential },
  { needle: 'who we are', image: siteImages.licenseCredential },
  { needle: 'transparency', image: siteImages.licenseCredential },
  { needle: 'integrity', image: siteImages.fairHousing },
  { needle: 'timeline', image: siteImages.constructionTimeline },
  { needle: 'builder negotiation', image: siteImages.builderAdvocate },
  { needle: 'advocacy', image: siteImages.builderAdvocate },
  { needle: 'energy', image: siteImages.energyEfficiency },
  { needle: 'solar', image: siteImages.energyEfficiency },
  { needle: 'specialist', image: siteImages.specialistStreet },
  { needle: 'local expert', image: siteImages.specialistStreet },
  { needle: 'local focus', image: siteImages.specialistStreet },
  { needle: 'local expertise', image: siteImages.specialistStreet },
  { needle: 'lifestyle', image: siteImages.propertyTypesMarket },
  { needle: 'browse by category', image: siteImages.propertyTypesMarket },
  { needle: 'property type', image: siteImages.propertyTypesMarket },
  { needle: 'buying resource', image: siteImages.buyerTour },
  { needle: 'selling resource', image: siteImages.sellerPrep },
  { needle: 'related market', image: siteImages.marketReport },
  { needle: 'incentive', image: siteImages.incentives },
  { needle: 'buydown', image: siteImages.incentives },
  { needle: 'lennar', image: siteImages.newConstruction },
  { needle: 'horton', image: siteImages.newConstruction },
  { needle: 'builder', image: siteImages.newConstruction },
  { needle: 'new construction', image: siteImages.newConstruction },
  { needle: 'tule', image: siteImages.tuleSprings },
  { needle: 'prominence', image: siteImages.prominence },
  { needle: 'paseos', image: siteImages.paseos },
  { needle: 'desert willow', image: siteImages.desertWillows },
  { needle: 'club aliante', image: siteImages.clubAliante },
  { needle: 'parks', image: siteImages.amenities },
  { needle: 'recreation', image: siteImages.amenities },
  { needle: 'amenit', image: siteImages.amenities },
  { needle: 'pool', image: siteImages.amenities },
  { needle: 'open-access', image: siteImages.paseos },
  { needle: 'open access', image: siteImages.paseos },
  { needle: 'tour', image: siteImages.villageTour },
  { needle: 'village', image: siteImages.villageTour },
  { needle: 'comps', image: siteImages.pricingComps },
  { needle: 'comparable', image: siteImages.pricingComps },
  { needle: 'cma', image: siteImages.pricingComps },
  { needle: 'pric', image: siteImages.pricingComps },
  { needle: 'rent', image: siteImages.rentalHoa },
  { needle: 'mortgage', image: siteImages.lenderMeeting },
  { needle: 'loan', image: siteImages.lenderMeeting },
  { needle: 'down payment', image: siteImages.lenderMeeting },
  { needle: 'office', image: siteImages.officeNap },
  { needle: 'nap', image: siteImages.officeNap },
  { needle: 'contact', image: siteImages.officeNap },
  { needle: 'frequently asked', image: siteImages.officeNap },
];

/**
 * Pick a heading-matched photo from H2/H3 text. Architecture and landscape only.
 * Fair Housing: never map “family,” “safe,” or school-quality language to a photo.
 */
export function headingMatchedImage(heading: string, fallback?: SiteImage): SiteImage {
  const h = heading.toLowerCase();
  const match = HEADING_PHOTO_MATCHES.find((row) => h.includes(row.needle));
  return match?.image ?? fallback ?? siteImages.neighborhoods;
}
