import {
  aboutFaqs,
  builderFaqs,
  builderHubFaqs,
  buyerFaqs,
  compareFaqs,
  contactFaqs,
  gatedFaqs,
  golfFaqs,
  homeFaqs,
  incentivesFaqs,
  investmentFaqs,
  legalFaqs,
  listingsFaqs,
  marketFaqs,
  mortgageFaqs,
  neighborhoodFaqs,
  neighborhoodHubFaqs,
  newConstructionFaqs,
  schoolsFaqs,
  searchFaqs,
  sellerFaqs,
  sunCityFaqs,
  valuationFaqs,
} from './page-faqs';
import type { PageDefinition } from './types';

const homeSections: PageDefinition['sections'] = [
  {
    id: 'hero',
    name: 'Aliante homes for sale hero',
    description: 'Primary H1 and MLS search entry.',
  },
  {
    id: 'search',
    name: 'Live MLS search',
    description: 'RealScout search widget for 89084 listings.',
  },
  {
    id: 'lifestyle',
    name: 'Homes by lifestyle',
    description: 'Gated, golf, new construction, and 55+ categories.',
  },
  {
    id: 'agent',
    name: 'Meet Dr. Jan Duffy',
    description: 'Hyperlocal agent introduction and credentials.',
  },
  {
    id: 'buyer-path',
    name: 'How to buy in Aliante',
    description: 'Search, tour, and close steps.',
  },
  {
    id: 'communities',
    name: 'Featured Aliante communities',
    description: 'Neighborhood cards with internal links.',
  },
  {
    id: 'services',
    name: 'Realtor services',
    description: 'Buyer, seller, new construction, and CMA services.',
  },
  {
    id: 'property-types',
    name: 'Property types',
    description: 'Resale, new construction, golf, and 55+ housing mix.',
  },
  {
    id: 'market',
    name: 'Aliante market snapshot',
    description: 'MLS-connected inventory narrative.',
  },
  {
    id: 'trust',
    name: 'License and brokerage',
    description: 'Nevada license and Berkshire Hathaway affiliation.',
  },
  { id: 'news', name: 'Latest market insights', description: 'Keeping Current Matters feed.' },
  { id: 'nearby', name: 'What’s nearby', description: 'Google Map of nearby Aliante places.' },
  {
    id: 'faq',
    name: 'Aliante real estate FAQ',
    description: 'Answer-engine questions about 89084 homes.',
  },
];

const listingSections: PageDefinition['sections'] = [
  { id: 'hero', name: 'Homes for sale hero' },
  { id: 'search', name: 'MLS search' },
  { id: 'categories', name: 'Property categories' },
  { id: 'snapshot', name: 'Market snapshot' },
  { id: 'tips', name: 'Search tips' },
  { id: 'faq', name: 'Listings FAQ' },
];

const neighborhoodDetailSections: PageDefinition['sections'] = [
  { id: 'hero', name: 'Neighborhood overview' },
  { id: 'listings', name: 'Featured MLS homes' },
  { id: 'amenities', name: 'Community amenities' },
  { id: 'detail', name: 'Neighborhood details' },
  { id: 'nearby-villages', name: 'Other Aliante neighborhoods' },
];

const builderDetailSections: PageDefinition['sections'] = [
  { id: 'hero', name: 'Builder overview' },
  { id: 'builders', name: 'Aliante builders' },
  { id: 'why', name: 'Why new construction' },
  { id: 'detail', name: 'Builder details' },
  { id: 'qmi', name: 'Quick move-in homes' },
];

export const pageCatalog: PageDefinition[] = [
  {
    path: '/',
    name: 'Aliante North Las Vegas Real Estate & Homes For Sale',
    description:
      'Browse Aliante homes for sale in North Las Vegas, NV 89084. MLS listings updated about every 15 minutes. Gated communities, Sun City Aliante 55+, new construction.',
    kind: 'home',
    pageTypes: ['WebPage', 'CollectionPage'],
    faqPlacement: 'inline',
    sections: homeSections,
    faqs: homeFaqs,
  },
  {
    path: '/homes-for-sale',
    name: 'Aliante Homes For Sale | North Las Vegas NV 89084 MLS Listings',
    description:
      'Browse Aliante homes for sale in North Las Vegas, NV 89084. MLS listings updated about every 15 minutes.',
    kind: 'listings',
    pageTypes: ['CollectionPage', 'WebPage'],
    faqPlacement: 'inline',
    sections: listingSections,
    faqs: listingsFaqs,
  },
  {
    path: '/search',
    name: 'Search Aliante Homes - Advanced MLS Search',
    description: 'Search Aliante homes with MLS filters. Updated about every 15 minutes.',
    kind: 'search',
    pageTypes: ['SearchResultsPage', 'WebPage'],
    faqPlacement: 'layout',
    sections: [
      { id: 'hero', name: 'Search hero' },
      { id: 'filters', name: 'Advanced MLS filters' },
      { id: 'results', name: 'Search guidance' },
      { id: 'categories', name: 'Property categories' },
    ],
    faqs: searchFaqs,
  },
  {
    path: '/new-construction',
    name: 'New Construction Homes Aliante North Las Vegas',
    description:
      'New construction in Aliante from Lennar, D.R. Horton, Tri Pointe, Del Webb, Toll Brothers, and Richmond American, with independent buyer representation.',
    kind: 'collection',
    pageTypes: ['CollectionPage', 'WebPage'],
    faqPlacement: 'inline',
    serviceSlug: 'new-construction',
    sections: [
      { id: 'hero', name: 'New construction hero' },
      { id: 'builders', name: 'Top Aliante builders' },
      { id: 'why', name: 'Why buy new construction' },
      { id: 'process', name: 'Construction process' },
      { id: 'qmi', name: 'Quick move-in homes' },
      { id: 'compare', name: 'Builder comparison' },
      { id: 'faq', name: 'New construction FAQ' },
    ],
    faqs: newConstructionFaqs,
  },
  {
    path: '/neighborhoods',
    name: 'Aliante Neighborhoods Guide | North Las Vegas Communities',
    description:
      'Explore Aliante neighborhoods: The Prominence, Desert Willows, Club Aliante, The Paseos, Tule Springs, and Sun City Aliante.',
    kind: 'neighborhood-hub',
    pageTypes: ['CollectionPage', 'WebPage'],
    faqPlacement: 'layout',
    sections: [
      { id: 'hero', name: 'Neighborhoods hero' },
      { id: 'cards', name: 'Neighborhood cards' },
      { id: 'amenities', name: 'Community amenities' },
      { id: 'compare', name: 'Neighborhood comparison' },
    ],
    faqs: neighborhoodHubFaqs,
  },
  {
    path: '/neighborhoods/prominence',
    name: 'The Prominence Aliante - Luxury Gated Community',
    description:
      'The Prominence luxury gated community in Aliante with golf-course views and premium amenities.',
    kind: 'neighborhood',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    neighborhoodSlug: 'prominence',
    sections: neighborhoodDetailSections,
    faqs: neighborhoodFaqs('The Prominence'),
  },
  {
    path: '/neighborhoods/desert-willows',
    name: 'Desert Willows Aliante Homes For Sale',
    description:
      'Desert Willows homes in Aliante, North Las Vegas 89084. Parks, community pools, and a mix of floor plans.',
    kind: 'neighborhood',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    neighborhoodSlug: 'desert-willows',
    sections: neighborhoodDetailSections,
    faqs: neighborhoodFaqs('Desert Willows'),
  },
  {
    path: '/neighborhoods/club-aliante',
    name: 'Club Aliante Golf Course Homes',
    description: 'Golf-course living in Club Aliante with clubhouse access and gated streets.',
    kind: 'neighborhood',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    neighborhoodSlug: 'club-aliante',
    sections: neighborhoodDetailSections,
    faqs: neighborhoodFaqs('Club Aliante'),
  },
  {
    path: '/neighborhoods/paseos',
    name: 'The Paseos Aliante Homes For Sale',
    description:
      'The Paseos gated community in Aliante with resort-style amenities and a range of home sizes.',
    kind: 'neighborhood',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    neighborhoodSlug: 'paseos',
    sections: neighborhoodDetailSections,
    faqs: neighborhoodFaqs('The Paseos'),
  },
  {
    path: '/neighborhoods/tule-springs',
    name: 'Villages at Tule Springs New Construction',
    description: 'New construction near Floyd Lamb Park and Tule Springs in North Las Vegas.',
    kind: 'neighborhood',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    neighborhoodSlug: 'tule-springs',
    sections: neighborhoodDetailSections,
    faqs: neighborhoodFaqs('Villages at Tule Springs'),
  },
  {
    path: '/neighborhoods/sun-city',
    name: 'Sun City Aliante 55+ Active Adult Community',
    description:
      'Del Webb Sun City Aliante 55+ homes with golf, clubs, and low-maintenance living.',
    kind: 'neighborhood',
    pageTypes: ['WebPage'],
    faqPlacement: 'none',
    neighborhoodSlug: 'sun-city',
    sections: neighborhoodDetailSections,
  },
  {
    path: '/neighborhoods/compare',
    name: 'Compare Aliante Neighborhoods',
    description: 'Side-by-side comparison of Aliante villages, amenities, and housing mix.',
    kind: 'neighborhood-compare',
    pageTypes: ['WebPage', 'CollectionPage'],
    faqPlacement: 'layout',
    sections: [
      { id: 'hero', name: 'Compare hero' },
      { id: 'table', name: 'Neighborhood comparison table' },
    ],
    faqs: compareFaqs,
  },
  {
    path: '/sun-city-aliante',
    name: 'Sun City Aliante 55+ Community',
    description: 'Del Webb Sun City Aliante 55+ active-adult community in North Las Vegas 89084.',
    kind: 'collection',
    pageTypes: ['CollectionPage', 'WebPage'],
    faqPlacement: 'layout',
    neighborhoodSlug: 'sun-city',
    serviceSlug: '55-plus',
    sections: [
      { id: 'hero', name: 'Sun City hero' },
      { id: 'content', name: '55+ community details' },
      { id: 'listings', name: 'Current homes' },
    ],
    faqs: sunCityFaqs,
  },
  {
    path: '/gated-communities',
    name: 'Gated Communities in Aliante',
    description:
      'Gated Aliante neighborhoods with controlled access and private amenities, including The Prominence and Club Aliante.',
    kind: 'collection',
    pageTypes: ['CollectionPage', 'WebPage'],
    faqPlacement: 'layout',
    sections: [
      { id: 'hero', name: 'Gated communities hero' },
      { id: 'content', name: 'Gated living details' },
      { id: 'neighborhoods', name: 'Gated villages' },
    ],
    faqs: gatedFaqs,
  },
  {
    path: '/golf-homes',
    name: 'Golf Course Homes Aliante',
    description: 'Homes near Club Aliante and Aliante Golf Club in North Las Vegas 89084.',
    kind: 'collection',
    pageTypes: ['CollectionPage', 'WebPage'],
    faqPlacement: 'layout',
    sections: [
      { id: 'hero', name: 'Golf homes hero' },
      { id: 'content', name: 'Fairway living details' },
    ],
    faqs: golfFaqs,
  },
  {
    path: '/builders',
    name: 'New Construction Builders in Aliante',
    description:
      'Compare Lennar, D.R. Horton, Tri Pointe, Del Webb, Toll Brothers, and Richmond American in Aliante.',
    kind: 'builder-hub',
    pageTypes: ['CollectionPage', 'WebPage'],
    faqPlacement: 'layout',
    serviceSlug: 'new-construction',
    sections: [
      { id: 'hero', name: 'Builders hero' },
      { id: 'intro', name: 'Builder overview' },
      { id: 'list', name: 'Top builders' },
      { id: 'compare', name: 'Builder comparison' },
      { id: 'incentives', name: 'Incentive overview' },
    ],
    faqs: builderHubFaqs,
  },
  {
    path: '/builders/lennar',
    name: 'Lennar Homes Aliante',
    description:
      'Lennar new construction in Aliante with Everything’s Included packages and independent buyer representation.',
    kind: 'builder',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    builderSlug: 'lennar',
    sections: builderDetailSections,
    faqs: builderFaqs('Lennar'),
  },
  {
    path: '/builders/dr-horton',
    name: 'D.R. Horton Homes Tule Springs',
    description: 'D.R. Horton new construction near Tule Springs with independent buyer advocacy.',
    kind: 'builder',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    builderSlug: 'dr-horton',
    sections: builderDetailSections,
    faqs: builderFaqs('D.R. Horton'),
  },
  {
    path: '/builders/tri-pointe',
    name: 'Tri Pointe Homes Aliante',
    description: 'Tri Pointe Homes new construction in the Aliante / North Las Vegas 89084 area.',
    kind: 'builder',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    builderSlug: 'tri-pointe',
    sections: builderDetailSections,
    faqs: builderFaqs('Tri Pointe Homes'),
  },
  {
    path: '/builders/del-webb',
    name: 'Del Webb Sun City Aliante',
    description:
      'Del Webb 55+ homes in Sun City Aliante with golf, clubs, and low-maintenance plans.',
    kind: 'builder',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    builderSlug: 'del-webb',
    neighborhoodSlug: 'sun-city',
    sections: builderDetailSections,
    faqs: builderFaqs('Del Webb'),
  },
  {
    path: '/builders/toll-brothers',
    name: 'Toll Brothers Luxury Homes Aliante',
    description:
      'Toll Brothers luxury new construction serving the Aliante / North Las Vegas market.',
    kind: 'builder',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    builderSlug: 'toll-brothers',
    sections: builderDetailSections,
    faqs: builderFaqs('Toll Brothers'),
  },
  {
    path: '/builders/richmond-american',
    name: 'Richmond American Homes Aliante',
    description: 'Richmond American Homes new construction in Aliante and North Las Vegas.',
    kind: 'builder',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    builderSlug: 'richmond-american',
    sections: builderDetailSections,
    faqs: builderFaqs('Richmond American Homes'),
  },
  {
    path: '/builders/incentives',
    name: 'Aliante Builder Incentives Tracker',
    description:
      'Current-style builder credits, buydowns, and design-center offers for Aliante new construction.',
    kind: 'incentives',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    serviceSlug: 'new-construction',
    sections: [
      { id: 'hero', name: 'Incentives hero' },
      { id: 'tracker', name: 'Incentive details' },
    ],
    faqs: incentivesFaqs,
  },
  {
    path: '/market-report',
    name: 'Aliante Market Report',
    description:
      'Aliante MLS market snapshot: inventory, pricing context, and days-on-market from live widgets.',
    kind: 'dataset',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    sections: [
      { id: 'hero', name: 'Market report hero' },
      { id: 'snapshot', name: 'MLS snapshot' },
      { id: 'analysis', name: 'Market analysis' },
    ],
    faqs: marketFaqs,
  },
  {
    path: '/buyer-guide',
    name: 'Aliante Home Buyer Guide',
    description:
      'Step-by-step guide to buying in Aliante, North Las Vegas 89084, with local agent support.',
    kind: 'howto',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    serviceSlug: 'buyer-representation',
    sections: [
      { id: 'hero', name: 'Buyer guide hero' },
      { id: 'guide', name: 'Buying steps' },
      { id: 'tips', name: 'Search tips' },
      { id: 'process', name: 'Closing process' },
    ],
    faqs: buyerFaqs,
    howTo: {
      name: 'How to buy a home in Aliante, North Las Vegas',
      description:
        'Search MLS listings, tour Aliante communities, and close with a hyperlocal agent.',
      steps: [
        {
          name: 'Search live MLS',
          text: 'Browse Aliante homes updated about every 15 minutes.',
        },
        {
          name: 'Tour communities',
          text: 'Compare gated, golf, 55+, and new-construction neighborhoods.',
        },
        {
          name: 'Get local guidance',
          text: 'Work with Dr. Jan Duffy on offers, inspections, and closing.',
        },
      ],
    },
  },
  {
    path: '/seller-checklist',
    name: 'Aliante Home Selling Checklist',
    description: 'Checklist to prepare, price, and market an Aliante home using 89084 comps.',
    kind: 'howto',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    serviceSlug: 'seller-representation',
    sections: [
      { id: 'hero', name: 'Seller checklist hero' },
      { id: 'checklist', name: 'Selling checklist' },
    ],
    faqs: sellerFaqs,
    howTo: {
      name: 'How to sell a home in Aliante',
      description:
        'Prepare, price, and list an Aliante home with neighborhood comps and MLS marketing.',
      steps: [
        {
          name: 'Complete a CMA and repairs',
          text: 'Price against recent 89084 solds and finish safety and presentation repairs before photos.',
        },
        {
          name: 'Stage, photograph, and list on MLS',
          text: 'Use professional media and accurate HOA remarks so buyers and agents can filter correctly.',
        },
        {
          name: 'Negotiate, inspect, and close',
          text: 'Manage offers, inspection requests, and title through closing with local vendor coordination.',
        },
      ],
    },
  },
  {
    path: '/home-valuation',
    name: 'Free Aliante Home Valuation',
    description:
      'Request a comparative market analysis for an Aliante, North Las Vegas 89084 property.',
    kind: 'service',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    serviceSlug: 'home-valuation',
    sections: [
      { id: 'hero', name: 'Valuation hero' },
      { id: 'form', name: 'CMA request form' },
    ],
    faqs: valuationFaqs,
  },
  {
    path: '/mortgage-calculator',
    name: 'Aliante Mortgage Payment Calculator',
    description:
      'Estimate principal and interest for Aliante homes. Not a rate lock or lender offer.',
    kind: 'calculator',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    sections: [
      { id: 'hero', name: 'Calculator hero' },
      { id: 'calculator', name: 'Payment calculator' },
      { id: 'form', name: 'Talk to an agent' },
    ],
    faqs: mortgageFaqs,
  },
  {
    path: '/investment-analysis',
    name: 'Aliante Investment Property Analysis',
    description:
      'Rental and appreciation context for Aliante investors, with HOA and lease-rule caveats.',
    kind: 'service',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    serviceSlug: 'investment-analysis',
    sections: [
      { id: 'hero', name: 'Investment hero' },
      { id: 'snapshot', name: 'Market snapshot' },
      { id: 'analysis', name: 'Investment analysis' },
    ],
    faqs: investmentFaqs,
  },
  {
    path: '/schools',
    name: 'Aliante Schools Guide',
    description:
      'Named schools serving Aliante addresses, including Leavitt, Kit Carson, Homer, Brinley, Centennial, and Legacy. Verify boundaries with CCSD.',
    kind: 'schools',
    pageTypes: ['WebPage'],
    faqPlacement: 'layout',
    sections: [
      { id: 'hero', name: 'Schools hero' },
      { id: 'elementary', name: 'Elementary schools' },
      { id: 'secondary', name: 'Middle and high schools' },
    ],
    faqs: schoolsFaqs,
  },
  {
    path: '/about',
    name: 'About Dr. Jan Duffy | Aliante Real Estate',
    description:
      'Licensed Aliante specialist since 2018 with Berkshire Hathaway HomeServices Nevada Properties.',
    kind: 'about',
    pageTypes: ['AboutPage', 'WebPage'],
    faqPlacement: 'inline',
    sections: [
      { id: 'hero', name: 'About hero' },
      { id: 'stats', name: 'Experience snapshot' },
      { id: 'expertise', name: 'Aliante expertise' },
      { id: 'faq', name: 'About FAQ' },
    ],
    faqs: aboutFaqs,
  },
  {
    path: '/contact',
    name: 'Contact, Directions & Nearby | Aliante Real Estate',
    description:
      'Visit 2590 Nature Park Drive, Suite 275, North Las Vegas, NV 89084 or call (702) 707-7273.',
    kind: 'contact',
    pageTypes: ['ContactPage', 'WebPage'],
    faqPlacement: 'inline',
    sections: [
      { id: 'hero', name: 'Contact hero' },
      { id: 'methods', name: 'Call, email, and form' },
      { id: 'office', name: 'Office map and hours' },
      { id: 'nearby', name: 'What’s nearby' },
      { id: 'faq', name: 'Contact FAQ' },
    ],
    faqs: contactFaqs,
  },
  {
    path: '/privacy-policy',
    name: 'Privacy Policy',
    description: 'Privacy practices for Aliante Homes For Sale.',
    kind: 'legal',
    pageTypes: ['WebPage'],
    faqPlacement: 'none',
    sections: [{ id: 'policy', name: 'Privacy policy' }],
    faqs: legalFaqs,
  },
  {
    path: '/terms-of-service',
    name: 'Terms of Service',
    description: 'Terms of use for Aliante Homes For Sale.',
    kind: 'legal',
    pageTypes: ['WebPage'],
    faqPlacement: 'none',
    sections: [{ id: 'terms', name: 'Terms of service' }],
  },
  {
    path: '/accessibility',
    name: 'Accessibility Statement',
    description: 'Accessibility statement for Aliante Homes For Sale.',
    kind: 'legal',
    pageTypes: ['WebPage'],
    faqPlacement: 'none',
    sections: [{ id: 'statement', name: 'Accessibility statement' }],
  },
  {
    path: '/fair-housing',
    name: 'Fair Housing Statement',
    description: 'Fair Housing statement for Aliante Homes For Sale.',
    kind: 'legal',
    pageTypes: ['WebPage'],
    faqPlacement: 'none',
    sections: [{ id: 'statement', name: 'Fair housing statement' }],
  },
];

export const pageCatalogByPath: Record<string, PageDefinition> = Object.fromEntries(
  pageCatalog.map((page) => [page.path, page])
);
